### ISSUE TITLE
Problems in Setting up the SCION Development Environment

### ISSUE THREAD

**Issue by alicecuii** [scionproto/scion#4365] opened 2023-07-12 12:36 UTC
I am following the steps in https://docs.scion.org/en/latest/dev/setup.html and using a Ubuntu 18.04 LTS machine from Equinix. 
I am also running as a non-root user with sudo access.
In Step 3, `./tools/install_deps`, I face an error: ![image](https://github.com/scionproto/scion/assets/47451060/b54aa69d-8688-4877-a636-bb919c9dee4f)
So I change the version in bazel-remote.yml to 3.3 (or 2.2).
Then when I run `make`, I face errors as below:
<img width="1242" alt="Screenshot 2023-07-12 at 8 35 09 PM" src="https://github.com/scionproto/scion/assets/47451060/86b68771-b2f6-4a54-9c06-13ae080bcae8">

I tried to clear the Bazel cache and rerun the make multiple times but it doesn't work.

**Comment by oncilla** [comment] 2023-07-12 13:59
Hi @alicecuii 

For the first version, could you please tell us which docker compose version you are working with on that VM?

The make errors you see were caused by one of our dependencies suddenly disappearing (see #4362 for more details).
You can cherry-pick that commit and the build should work again. I will make sure it gets merged soon.

**Comment by oncilla** [comment] 2023-07-12 14:34
PR has been merged. Just pull the latest changes and you should be good to go

**Comment by alicecuii** [comment] 2023-07-12 14:43
> PR has been merged. Just pull the latest changes and you should be good to go

Yes, there's no errors now. Thank you!

To answer your first question, my docker-compose version is `docker-compose version 1.17.1, build unknown`

**Comment by oncilla** [comment] 2023-07-12 15:08
Looks like your docker-compose version is to old and does not support the compose file version yet: https://github.com/docker/compose/releases/tag/1.17.1

Given ubuntu 18.04 is EOL, I would suggest you upgrade to something more recent.

**Comment by alicecuii** [comment] 2023-07-13 05:04
> Looks like your docker-compose version is to old and does not support the compose file version yet: https://github.com/docker/compose/releases/tag/1.17.1
> 
> ~Given ubuntu 18.04 is EOL, I would suggest you upgrade to something more recent.~
> 
> I guess we should update our docs to not recommend 18.04 @matzf

According to the docker docs, Compose V1 (which is docker-compose) stopped receiving updates. Maybe you can consider using Compose V2 (which is docker compose without '-') instead. However, I found that the Compose V2 did not fit in SCION environment.

**Comment by oncilla** [comment] 2023-07-13 06:48
FWIW, the `./tools/install_docker` script installs compose V2 already:

https://github.com/scionproto/scion/blob/00835ed735ebd246d9f6dbaece0319f898325ac9/tools/install_docker#L29-L38

**Comment by oncilla** [comment] 2023-08-17 09:08
Hi @alicecuii 

Have you managed to set up the environment, or is there something else we can help you with?

If not, we can close the issue if all your problems have been resolved.

**Comment by alicecuii** [comment] 2023-08-17 09:46
> Hi @alicecuii
> 
> Have you managed to set up the environment, or is there something else we can help you with?
> 
> If not, we can close the issue if all your problems have been resolved.

I have set up the environment successfully. Thank you!

**Closed** 2023-08-17 10:01 UTC
Labels: bug
