### ISSUE TITLE
Possible race condition when BFD packets are processed

### ISSUE THREAD

**Issue by LinoTelschow** [scionproto/scion#4131] opened 2021-11-18 23:35 UTC
Hi all,

I think I have found a possible race condition that may appear if a router is under heavy load.

The `processPkt` method takes as input argument a buffer that is being reused.
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/pkg/router/dataplane.go#L473
Now, if a BFD packet is received, it is here decoded to a SCION packet.
Then if `processIntraBFD` is called, it receives the parameter `pld`. `pld` itself is a sub-slice of `p.rawPkt` (`p.lastLayer.LayerPayload()` returns a sub-slice of `p.rawPkt`) and `p.rawPkt` is set to `p.Buffers[0][:p.N]`
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/pkg/router/dataplane.go#L597-L616
Now, the `processIntraBFD` method deserializes `pld` to a BFD packet. However the `DecodeFromBytes` method embeds some sub-slices of `pld` in the BFD packet. The BFD packet is then sent to a Message channel. The thread that receives the packet from the channel then obtains a BFD packet which contains sub-slices of `p.Buffers[0][:p.N]`. Now If the router receives many messages, the buffer will be reused and will overwrite fields in the BFD packet.
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/pkg/router/dataplane.go#L655-L675

**Comment by matzf** [comment] 2021-11-19 08:34
Great catch! :eye: :eye: 

From quickly going through the code, it appears that all the data we're accessing in `*layers.BFD` are stored as copied values and so is safe to be processed asynchronously. Apart from the `BaseLayer.Contents` (which we don't appear to access), only the `AuthHeader.Data` appears to be stored as a slice referencing the underlying packet data -- and the auth header is explicitly not supported in the router anyway.

This is still a lurking issue though -- one possible fix would be to add our own struct definition for a BFD packet, containing only the data that we do need to process and no slices of the original packet data, that can be safely passed in the channel.

**Comment by oncilla** [comment] 2021-11-19 09:19
@LinoTelschow Nice find.

To be on the safe side, we should address this.

I propose we simply copy the payload before parsing it, for this we would need to edit the following two lines:
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/pkg/router/dataplane.go#L625
https://github.com/scionproto/scion/blob/362c4622084037cd1d3ac593d2d78128a86638fd/go/pkg/router/dataplane.go#L615

Here we could replace `pld` with `append([]byte(nil), pld...)`.

If you want to, you can create a pull request with this fix, as it is your find.
(If not, I will create a fix for this.)

**Comment by LinoTelschow** [comment] 2021-11-19 09:40
I tried to push this simple fix, but it seems I don't have write access to this repo.

**Comment by matzf** [comment] 2021-11-19 09:49
@oncilla sure that works, but that seems rather heavy handed. We shouldn't add even more (unnecessary) copies and allocations to the router dataplane.
Instead, we could take this as an opportunity to improve the interface between the router dataplane and the router/bfd/session; for example, we can do most of the BFD packet validation synchronously in the dataplane, and then only a small set of relevant values need to be passed to the asynchronous processing in the `Session` itself. This allows to recycle the `layers.BFD` object for parsing in the dataplane and the size of the data passed over the channel is minimized.

**Comment by oncilla** [comment] 2021-11-19 12:47
@LinoTelschow you need to create a pull request 

@matzf Honestly, I'm not to worried about allocations in BFD packets, they make for such a low volume of traffic anyway.
I'm sure there are lower hanging fruits to optimize here.

**Comment by LinoTelschow** [comment] 2021-11-19 12:58
@oncilla For this I must first push my branch. But this fails, since I don't have write access:
![image](https://user-images.githubusercontent.com/36457952/142626605-5d7b1567-cf14-40a7-bc9d-49027479eb16.png)

**Comment by oncilla** [comment] 2021-11-19 13:18
@LinoTelschow The default workflow for contributing on GitHub is to create a fork and create a PR from there.

We have some docs on this here: https://scion.docs.anapaya.net/en/latest/contribute/git.html#how-to-use-git-and-github

The official GitHub docs, you can find here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

A general step-by-step guide, you can find here: https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by matzf** [comment] 2021-11-19 14:09
> @matzf Honestly, I'm not to worried about allocations in BFD packets, they make for such a low volume of traffic anyway.
I'm sure there are lower hanging fruits to optimize here.

We run ASes with 100s of interfaces which amounts to 1000s of BFD messages per second. This is still a small number in the grand scheme of things, but it's enough to make the allocations of the `layers.BFD` object (96 bytes) appear as a not-totally-insignificant value in the allocations tracker (0.6% of total allocation volume). Making a copy of the full packet first would at least double that, and this would bring the allocations caused by process*BFD into roughly the same area as the many of the existing problems during the processing of SCION packets, all of which seem to be harder to solve (stuff like: `GetHopField` allocates because it returns a pointer instead a small value, `slayers.SCION.DecodeFromBytes` always allocates a new path, etc.; changing these is a bunch more work).

By the way, looking at the bigger picture, the BFD sessions are responsible for over 50% of all the allocations in this router instance (seems to allocate new buffer for each packet it sends, plus something wrong counter labels). That's a lot of garbage to collect.

As this is not an urgent issue to solve, we can take the time to fix it as well as possible.

**Comment by oncilla** [comment] 2021-11-19 14:35
@matzf feel free to contribute a proposal/fix how to reduce allocations.
On our side, we do not have the resources currently to optimize the posix-router allocations.

**Closed** 2022-03-12 15:08 UTC
